Only build ck_fused_attn when aiter supported V3 ASM architectures found
Now we will skip building ck_fused_attn when no aiter supported V3 ASM
architectures found, as it replies on `libmha_fwd.so` and `libmha_bwd.so`.

Currently, the code will pass empty `GPU_ARCHS` environment variable to
aiter builder, which causes it to error out:

```log
File "TransformerEngine/3rdparty/aiter/aiter/jit/utils/chip_info.py", line 77, in get_gfx_custom_op_core
  raise KeyError(
KeyError: 'Unknown GPU architecture: . Supported architectures: [0, 1, 2, 3, 4, 5, 6, 7, 8]'
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>