Add definition for te_fp8_fnuz when ROCm version is 6.2
Before https://github.com/ROCm/clr/commit/353f15afa6cfb0fc1eebbc618be47e0cb639c321
(In ROCm6.2), FP8 OCP is not added and the code implementation
is in FNUZ, so we define `te_fp8_fnuz()` to return true, to
fix the following error:

```logs
transformer_engine/common/recipe/delayed_scaling.hip:42:14: error: use of undeclared identifier 'te_fp8_fnuz'
     42 |       return te_fp8_fnuz() ? 240 : 448;
        |              ^
  1 error generated when compiling for gfx90a.
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>