Fix te_fp8_fnuz undefined when ROCm version is 6.2
Before https://github.com/ROCm/clr/commit/353f15afa6cfb0fc1eebbc618be47e0cb639c321
(In ROCm6.2), FP8 OCP is not added and the code implementation is in FNUZ, so we
define `te_fp8_fnuz()` to return true, to fix the following error:

```log
  In file included from TransformerEngine/transformer_engine/pytorch/csrc/extensions_hip.h:15:
  TransformerEngine/transformer_engine/pytorch/csrc/common_hip.h:189:14: error: use of undeclared identifier 'te_fp8_fnuz'
    189 |       return te_fp8_fnuz()? at::kFloat8_e4m3fnuz : at::kFloat8_e4m3fn;
        |              ^
  TransformerEngine/transformer_engine/pytorch/csrc/common_hip.h:195:14: error: use of undeclared identifier 'te_fp8_fnuz'
    195 |       return te_fp8_fnuz()? at::kFloat8_e5m2fnuz : at::kFloat8_e5m2;
        |              ^
  2 errors generated when compiling for gfx90a.
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>