Avoid early call of `is_cdna4`
Similar to #183, Let's not call `is_fp8_fnuz` outside any function,
as that will call `triton.runtime.driver.active.get_current_target()`
as soon as importing, and that might be too early to call, since the
`CUDA/HIP/ROCM_VISIBLE_DEVICES` may not be set properly at this stage.

```log
  File "megatron/core/__init__.py", line 3, in <module>
    import megatron.core.tensor_parallel
  File "megatron/core/tensor_parallel/__init__.py", line 4, in <module>
    from .layers import (
  File "megatron/core/tensor_parallel/layers.py", line 27, in <module>
    from ..transformer.utils import make_sharded_tensors_for_checkpoint
  File "megatron/core/transformer/__init__.py", line 6, in <module>
    from .transformer_layer import TransformerLayer, TransformerLayerSubmodules
  File "megatron/core/transformer/transformer_layer.py", line 16, in <module>
    from megatron.core.transformer.cuda_graphs import CudaGraphManager
  File "megatron/core/transformer/cuda_graphs.py", line 15, in <module>
    from megatron.core.tensor_parallel.random import (
  File "megatron/core/tensor_parallel/random.py", line 26, in <module>
    import transformer_engine  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformer_engine/__init__.py", line 32, in <module>
    if _use_pytorch: from . import pytorch
                     ^^^^^^^^^^^^^^^^^^^^^
  File "transformer_engine/pytorch/__init__.py", line 69, in <module>
    from transformer_engine.pytorch.module import LayerNormLinear
  File "transformer_engine/pytorch/module/__init__.py", line 6, in <module>
    from .layernorm_linear import LayerNormLinear
  File "transformer_engine/pytorch/module/layernorm_linear.py", line 21, in <module>
    from .base import (
  File "transformer_engine/pytorch/module/base.py", line 26, in <module>
    from ._common import _ParameterInitMeta
  File "transformer_engine/pytorch/module/_common.py", line 27, in <module>
    from ..triton_kernels.layernorm import te_layernorm_bwd_triton
  File "transformer_engine/pytorch/triton_kernels/layernorm.py", line 12, in <module>
    from .common import (
  File "transformer_engine/pytorch/triton_kernels/common.py", line 15, in <module>
    torch_e4m3_type = torch.float8_e4m3fn if is_cdna4() else torch.float8_e4m3fnuz
                                             ^^^^^^^^^^
  File "transformer_engine/pytorch/triton_kernels/common.py", line 13, in is_cdna4
    return triton.runtime.driver.active.get_current_target().arch == "gfx950"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "triton/runtime/driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "triton/runtime/driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "triton/runtime/driver.py", line 8, in _create_driver
    raise RuntimeError(f"{len(actives)} active drivers ({actives}). There should only be one.")
RuntimeError: 0 active drivers ([]). There should only be one.
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>